### ISSUE TITLE
Add tooltips to x-axis tick labels in visit chart.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#112]
# Test notes
* X-axis tick label tooltips in visit chart should match column header tooltips in listing, i.e. they should display the visit and a breakdown of visit statuses at that visit.

**Comment by dschwentker** [comment]
Tested and passed. NOTE: the tooltips aren't quite right in the final commit for https://github.com/RhoInc/participant-visit-listing/pull/113, but they do appear to be correct in the final commit for https://github.com/RhoInc/participant-visit-listing/pull/116, so I'm passing this on the assumption that they will be correct in the final dev-v1.4.0 PR for regression testing.
