### ISSUE TITLE
Points on the far right get cut off.

### ISSUE THREAD

**Issue by rchronowic** [RhoInc/participant-visit-listing#120]
Points on the far right of the chart are cut in half.

![image](https://user-images.githubusercontent.com/42471621/63100045-3c307200-bf44-11e9-8a59-9c5cebc159da.png)

# Test notes
* Verify that points are not cut off on the edges of the chart canvas in the Study Day Chart.

**Comment by samussiah** [comment]
Need to expand the clip path to prevent that cutoff
