### ISSUE TITLE
Change text of legend

### ISSUE THREAD

**Issue by rchronowic** [RhoInc/participant-visit-listing#16]
DMEDS group would like to edit the text in the legend at the top.

For the black text: currently states "In Window", change to say "Entered".
For the blue text: currently states "Expected", change to "Future".

**Comment by samussiah** [comment]
The legend is data-driven.  @rchronowic , would you ask the DMEDS team to apply this change in the data?  Specifically I'm pulling visit status from the column `visit_status`.
