### ISSUE TITLE
Data-Driven Icon labels

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/participant-visit-listing#31]
Form DMEDS group. Requested data-driven legend info icon labels so that they could pass the desired text in. Would just be another column - although there will unfortunately be a lot of repetition.

# Test notes
* The visit status legend info icons (**ⓘ**) have tooltips that match the contents of the _visit_status_description_ column in the [data](https://github.com/RhoInc/viz-library/blob/master/data/dataCleaning/visits/dmv_Visits.csv).

**Comment by samussiah** [comment]
defaulting to `visit_status_description_col: 'visit_status_description'`
