### ISSUE TITLE
Adding back visit columns when changing filters while analysis subset is applied

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/participant-visit-listing#59]
Currently, when you select an analysis subset the visits are subset to the visits relevant to that analysis subset _and_ other filters. However, I'm not sure you can get those visits back without deselecting the analysis subset.

E.g. Select 'Screen Failure' then add an analysis filter. Then highlight the other Participant Status options and notice how only screening visit (or less) remains available although other visits have information.

# Test notes
* Filter interactions, particularly between the analysis subsets and the other filters, should update the listing columns and charts per expectation.

**Comment by samussiah** [comment]
good catch!
