### ISSUE TITLE
Add a long name visit variable in addition to an abbreviated one.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#73]
# Test notes
* When `abbreviate_visits` is set to `true`, the x-axis tick labels in the Visit Chart and the column headers in the Listing should display abbreviated visit values.  Every tooltip you can think of should display the full visit name though.
* When `abbreviate_visits` is set to `false`, the x-axis tick labels in the Visit Chart and the column headers in the Listing should display the full visit name.

**Comment by samussiah** [comment]
actually added an abbreviated visit variable, defaulting to the full visit variable

**Comment by dschwentker** [comment]
Tested and passed.
