### ISSUE TITLE
Figure out a better way to explain open cells/circles (visit expectation).

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#74]
# Test notes
* Verify a mark legend appears in the same container as the tabs.
* When the Visit Chart is active the legend should display rectangles.
* When the Study Day Chart is active the legend should display circles.
* When the Listing is active the legend should disappear.
* The labels in the legend should correspond to the visit statuses represented by that mark.

**Comment by samussiah** [comment]
add a second legend in the tabs container just below the visit status legend that distinguishes past and future visits

**Comment by dschwentker** [comment]
Tested and passed
