### ISSUE TITLE
Highlight all marks representing the same visit on click.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#76]
in _Schedule of Events by Study Day_, and fade all others

# Test notes
* Click a mark in the Study Day Chart.
  * Verify an annotation appears between the top x-axis and the chart that displays the selected visit name and the median study day of that visit.
  * Verify a vertical reference line appears corresponding to the median study day of that visit.
  * Verify the annotation and vertical reference line have tooltips that list the visit name, the median study day, summary statistics of the study day of that visit (n, min, median, max, mean, standard deviation), and an instruction detailing how to remove highlighting.
  * Verify all marks representing that visit are highlighted.
  * Verify horizontal reference lines appear connecting the marks to the vertical reference line.
  * Verify the horizontal reference lines have tooltips that list the number of days between that mark and the median reference study day, as well as an instruction detailing how to remove highlighting.
  * Verify all marks representing a different visit get faded, drank, Pour up (Drank), head shot (Drank) Sit down (Drank), stand up (Drank) Pass out (Drank), wake up (Drank) Faded (Drank), faded (Drank).
  * Verify clicking the annotation, the vertical reference line, the horizontal reference lines, or any highlighted mark removes all highlighting.

**Comment by dschwentker** [comment]
Tested and passed. NOTE: the summary statistics of the study day of that visit (n, min, median, max, mean, standard deviation) do not appear in the tooltip in the most recent commit for https://github.com/RhoInc/participant-visit-listing/pull/101, but they do appear in the most recent commit for https://github.com/RhoInc/participant-visit-listing/pull/116, so I'm passing this on the assumption they will be there in the final v1.4.0-dev commit as well for regression testing.
