### ISSUE TITLE
Optionalize analysis subsetters.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#77]
# Test notes
* Specify a nonexistent filter variable.  No filter representing that variable should appear and the webpage should render as expected.

![image](https://user-images.githubusercontent.com/5428548/54637579-529ed400-4a5f-11e9-80bc-d24d8c5f76db.png)

**Comment by danedexF5** [comment]
@samussiah works but it knocks out the 3 subset analysis filters. That seems like it should but wanted to make sure it was expected.
