### ISSUE TITLE
Move listing scrollbar from bottom to top.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#78]
# Test notes
* Verify a scrollbar appears above the listing (might have to zoom in).
* Verify scrolling the top scrollbar scrolls the bottom scrollbar.
* Verify scrolling the bottom scrollbar scrolls the top scrollbar.

**Comment by emmorris** [comment]
Heather noted in the 3-21-19 meeting that when there are a lot of subjects and a lot of visits the horizontal scroll bar is not very user friendly right now.  The scroll bar is at the very bottom of the listing so you have to scroll all the way to the bottom to move horizontally and see all the visits.  Ideally the user would be able to access it more easily.  One idea is to move it to the top of the listing.  This is not urgent.

**Comment by dschwentker** [comment]
Tested and passed
