### ISSUE TITLE
Add a toggle that displays dates in listing.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#86]
to make sorting visit columns chronologically more transparent.  currently visit status rather than visit date is displayed for past visits.

# Test notes
* Verify a checkbox labeled _Display visit dates_ displays in the top left of the listing container.
* When unchecked, the past visits should display visit status and future visits should display visit date.
* When checked, all visits should display visit date.

**Comment by dschwentker** [comment]
Tested and passed.
