### ISSUE TITLE
Set mouse cursor to loading while rendering and switching between displays.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#89]
so users don't update controls while the display is rendering

# Test notes
* The mouse cursor changes to the [wait icon](https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=wait) when loading:
  - on initialization
  - on tab change
  - on filter change

**Comment by emmorris** [comment]
This was requested by Heather via email on 4-18-19. She noted that it was confusing to users if they didn't see any indicator to let them know that the renderer was loading.  She would like the typical "Loading..." to be displayed when the chart is first loading and when you are switching between displays.

**Comment by samussiah** [comment]
define a loading class that applies to the entire webpage
```
            'html.wait, html.wait * {' +
                '    cursor: wait !important;' +
            '}',
```
then toggle that class everywhere loading is currently indicated:
```
            //indicate loading
            d3.select('html').classed('wait', true);
            context.containers.loading.classed('pvl-hidden', false);

            var loading = setInterval(function() {
                var loadingIndicated = context.containers.loading.style('display') !== 'none';

                if (loadingIndicated) {
                    //Handle loading indicator.
                    clearInterval(loading);
                    d3.select('html').classed('wait', false);
                    context.containers.loading.classed('pvl-hidden', true);
```

**Comment by dschwentker** [comment]
Load time is pretty fast, but I was able to get the mouse to change to the wait icon on occasion.
