### ISSUE TITLE
Add a destroy method.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#90]
That not only clears the contents of the containing element and the Webcharts object(s), but the stylesheet as well.

# Test notes
* Open the developer console.
*  On the Elements tab expand the `<head>` element and verify that the last child node is a `<style>` element and that its styles include _.participant-visit-listing_ classes.
* On the Console tab run `d3.select('.participant-visit-listing').node()` and verify the Participant Visit Listing `<div>` element is returned.
* Run `d3.select('.participant-visit-listing').datum().destroy()` and verify both the `<style>` element and `<div>` element are removed from the DOM.

Reference the images in [this crf-heat-map issue](https://github.com/RhoInc/crf-heat-map/issues/135) for screenshots.

**Comment by danedexF5** [comment]
Destroy method...DESTROYS
