### ISSUE TITLE
Add a search box to the visit chart.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/participant-visit-listing#91]
When looking at an actual subject it’s hard to see which line goes with what subject. You can search on the ‘Listing’ tab but you can’t see all the visits in one screen on that page easily like you can on the visit chart.

Would highlighting work, as in mousing over the subject label or in the chart highlights the row you're on?  Would the search box search on subject ID?  If so, would a subject ID filter be more appropriate?

# Test notes
* Verify that when mousing over the Visit Chart the x- and y-axis tick labels corresponding to the visit and participant of the cell underneath the mouse embolden.
* Verify that when mousing over the Study Day Chart the y-axis tick label corresponding to the participant of the row underneath the mouse emboldens, and that an x-axis tick label appears corresponding to the study day of the x-position of the mouse.

**Comment by dschwentker** [comment]
Tested and passed
